services:
  - type: web
    name: taskflow-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: singapore
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: Supabase__Url
        value: https://llkamzsucxfsundnvyze.supabase.co
      - key: Supabase__AnonKey
        value: sb_publishable_YEcgF1TQEnn31fR2AqK4Ag_v87Vy6ar
      - key: ConnectionStrings__DefaultConnection
        sync: false
